# Generated by Django 4.1.3 on 2022-12-12 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppUsuario', '0003_delete_postcriticas_delete_postnoticias'),
    ]

    operations = [
        migrations.CreateModel(
            name='PosteoList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=90)),
                ('subtitulo', models.CharField(max_length=90)),
                ('texto', models.CharField(max_length=254)),
                ('nombre', models.CharField(max_length=90)),
                ('email', models.CharField(max_length=50)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
