# Generated by Django 4.1.3 on 2022-12-22 14:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AppUsuario', '0007_alter_avatar_imagen_alter_usuario_imagen'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlbumImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='media/avatar/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppUsuario.usuario')),
            ],
        ),
    ]
