# Generated by Django 4.1.3 on 2022-12-23 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppUsuario', '0009_remove_usuario_name_alter_avatar_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='imagen',
        ),
    ]
